### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by ShadowVicky** [AnnaVechkaeva/multiword-expression-extraction#1]
I need your dataset.

**Comment by AnnaVechkaeva** [comment]
The dataset used was the German-English and Greek-English Europarl corpus, it's available at https://www.statmt.org/europarl/. Please, refer to the research paper cited in the readme (Koehn, Philipp. "Europarl: A parallel corpus for statistical machine translation." MT summit. Vol. 5. 2005.) for more details about the dataset
